/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Coupon { 'code' : string, 'discountAmount' : bigint }
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'couponUsed' : [] | [string],
  'customerPhone' : string,
  'productId' : bigint,
  'quantity' : bigint,
  'totalPrice' : bigint,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : bigint,
}
export interface _SERVICE {
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'initializeProducts' : ActorMethod<[], undefined>,
  'placeOrder' : ActorMethod<
    [bigint, bigint, [] | [string], string, string],
    Order
  >,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'validateCoupon' : ActorMethod<[string], Coupon>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];